#!/bin/bash

check_installed() {
    if [ -f "/usr/lib/checkany/checkany.py" ]; then
        return 0  # Já instalado
    else
        return 1  # Não instalado
    fi
}

clear
echo -e "\033[46;1;37m              ★ MENU CHECKUSER ★               \033[0m"
echo -e "\033[01;31m\033[0m"
echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 01 •\033[1;34m]\033[1;37m ➤  \033[1;33mINSTALAR CHECKUSER CONECTA4G \033[0m"
echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 02 •\033[1;34m]\033[1;37m ➤  \033[1;33mINSTALAR WS-EPRO \033[0m"
echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 03 •\033[1;34m]\033[1;37m ➤  \033[1;33mINSTALAR CHECKUSER DTUNNEL VPN\033[0m"
echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 04 •\033[1;34m]\033[1;37m ➤  \033[1;33mINSTALAR CHECKUSER MULTI-APPS VPN\033[0m"
echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 05 •\033[1;34m]\033[1;37m ➤  \033[1;33mINSTALAR PROXY DTUNNEL V2.0\033[0m"
echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 06 •\033[1;34m]\033[1;37m ➤  \033[1;33mINSTALAR conecta4g\033[0m"
echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 07 •\033[1;34m]\033[1;37m ➤  \033[1;33mINSTALAR CHECKUSER ANYVPN MOD\033[0m"
echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 00 •\033[1;34m]\033[1;37m ➤  \033[1;33mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
echo -e "\033[01;31m\033[0m"
echo -e "\033[0;36m░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░\033[0m"
tput civis
echo -ne "\033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : "
read x
tput cnorm
clear
case $x in
1 | 01)
    initcheck
    ;;
2 | 02)
    wget https://raw.githubusercontent.com/PhoenixxZ2023/ws-epro/main/Netcolvip.bin -O install-ws && chmod +x install-ws && ./install-ws && MENU
    ;;
3 | 03)
    bash <(curl -sL https://raw.githubusercontent.com/PhoenixxZ2023/DTCheckUser/master/install.sh)
    ;;
4 | 04)
    {
    curl -s -o instcheck.sh -L https://raw.githubusercontent.com/PhoenixxZ2023/checkUser2024/main/instcheck.sh
    chmod +x instcheck.sh
    ./instcheck.sh && chall
    echo "" 
    echo "SUPER CHECKUSER ATIVADO"
    }
    ;;
5 | 05)
    {
    curl -s -o install.sh -L https://raw.githubusercontent.com/PhoenixxZ2023/proxy/main/install.sh
    chmod +x install.sh
    ./install.sh && mainproxy
    echo ""
    echo "VELOCIDADE SUPREMA ATIVADA"
    }
    ;;
6 | 06)
    bash <(curl -sL https://raw.githubusercontent.com/PhoenixxZ2023/conecta/main/instcheck.sh) && chuser
    ;;
7 | 7)
    if check_installed; then
        chany  # Já instalado, executar o sistema chany
    else
        bash <(curl -sL https://raw.githubusercontent.com/PhoenixxZ2023/checkany/main/install.sh) && chany
    fi
    ;;
0 | 00)
    clear
    menu
    ;;
*)
    echo -e "\033[1;31mOpcao invalida!\033[0m"
    ;;
esac
sleep 2
