#!/bin/bash
    clear
    echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                 MENU HERRAMIENTAS PRO                   \033[1;33m \033[0m\033[01;31m║"
    echo -e "\033[01;31m║\033[0m"
    echo -e "\033[01;31m║\033[1;31m\033[1;34m[\033[1;37m 01 •\033[1;34m]\033[1;37m ➩  \033[1;33mINSTALAR UDP-CUSTOM \033[0m"
    echo -e "\033[01;31m║\033[1;31m\033[1;34m[\033[1;37m 02 •\033[1;34m]\033[1;37m ➩  \033[1;33mABRIR MENU UDP-CUSTOM \033[0m"
    echo -e "\033[01;31m║\033[1;31m\033[1;34m[\033[1;37m 03 •\033[1;34m]\033[1;37m ➩  \033[1;33mINSTALAR WEBSOCKET PRO \033[0m"
    echo -e "\033[01;31m║\033[1;31m\033[1;34m[\033[1;37m 04 •\033[1;34m]\033[1;37m ➩  \033[1;33mAUTO REBOOT (00:00H) \033[0m"
    echo -e "\033[01;31m║\033[1;31m\033[1;34m[\033[1;37m 00 •\033[1;34m]\033[1;37m ➩  \033[1;33mSAIR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
    echo -e "\033[01;31m║\033[0m"
    echo -e "\033[0;31m╠━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━═━\033[0m"
			tput civis
			echo -ne "\033[1;31m╰━━━━━━━━❪\033[1;32mSELECCIONE UNA OPCION\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			clear
                        sudo wget https://raw.githubusercontent.com/thefather12/UDP-PRO/main/install.sh; chmod +x install.sh; ./install.sh
			;;
                        2 | 02)
			udp
			;;
			3 | 03)
                        wget 'https://raw.githubusercontent.com/netfreeplus/ws-epro/main/Netcolvip.bin' -O 'install-ws' && chmod +x install-ws && ./install-ws
			;;
                        4 | 04)
			clear
                        echo -e "\E[44;1;37m             AUTO REBOOT              \E[0m"
                                echo -e "\033[1;31mESTA FUNCÃO ATIVA A REINICIALIZAÇÃO AUTOMATICA DE SUA VPS \033[1;33m \033[1;32\033[0m"
                        echo -e "\033[1;31mESOLHA UM HORÁRIO PARA AUTO-REBOOT: \033[1;33m00:00 \033[1;32\033[0m"
                     echo -ne "\033[1;32mDIGITE A HORA \033[1;33m\033[1;37m: "
                                 read escolha
                                     echo ""
                                     echo -e "\033[1;31m HORARIO VALIDO!"
                                     sleep 4
                                     clear
                        shutdown -r +$escolha
                        echo -e ""
                        echo -e "\033[1;33mAUTO REBOOT $escolha ACTIVADO COM EXITO \033[0m"
                        echo -e ""
                        echo -e "\033[1;34m[\033[1;37m01 •\033[1;34m]\033[1;37m > \033[1;33mDESACTIVAR REBOOT \033[1;37m\033[0;32m"
                        echo -e ""
                        echo -ne "\n\033[1;33mENTER \033[1;33mPARA VOLTAR\033[1;33mMENU!\033[0m"; read
                        ;;
                        1)
                        clear
                        echo -e "\E[44;1;37m             AUTO REBOOT              \E[0m"
                        echo -e "\033[1;31mESTA FUNCION DESACTIVA EL REINICIO AUTOMÁTICO DE TU VPS \033[1;33m \033[1;32\033[0m"
                        echo -e "\033[1;31mEL HORÁRIO PRÉ-DEFINIDO $escolha SERÁ DESACTIVADO \033[1;33m \033[1;32\033[0m"
                        shutdown -c
                     echo -e "\033[1;33mAUTO REBOOT DESACTIVADO CON EXITO \033[0m"
                     echo -e ""
                        echo -ne "\n\033[1;33mENTER \033[1;33mPARA VOLVER AL \033[1;33mMENU!\033[0m"; read
                        ;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcion invalida !\033[0m"
			sleep 2
			;;
			esac
		done
	}
	fun_conexao
}
